# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e794cc2536cac8210715e374f77d6b35d364f6a7bd1e779daccf4a2b82ad623865d9a2d6b05208ab80a97c36bafd9fae95846387d7305ab7b4d38305867dc00b
  facebook_sdk: <%= ENV["FACEBOOK_SDK"] %>
  facebook_id: 306635796018920
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_secret: <%= ENV['facebook_secret'] %>
  truppiemail_domain: truppie.com
  truppiemail_username: foo
  truppiemail_password: test
  redis_url: "redis://localhost:6379"
  stripe_key: <%= ENV['STRIPE_KEY'] %>
  stripe_pubkey: <%= ENV['STRIPE_PUBKEY'] %>
  devise_secret_key: aaaa
  local_key: <%= ENV['LOCAL_KEY'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_email_alt: <%= ENV['ADMIN_EMAIL_ALT'] %>
  amadeus_api_key: <%= ENV['AMADEUS_API_KEY'] %>
  mailchimp_api_key: bfb6ab177d512a5353a0edc4284da115-us18
  mailchimp_list_id: 9d2cbb6eda

test:
  secret_key_base: 645b2a9bd42bb2c8351896f18bec4391d27fb2dc23036bf3883dd21a330bc72f638e09445dc1d02f45bb15842bb7a932c4ecea6edffa3bc73abbdf578d381c33
  facebook_id: 1234
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_sdk: sdkid
  facebook_secret: 5678
  truppiemail_domain: whatever.com
  truppiemail_username: foo
  truppiemail_password: test
  redis_url: "redis://localhost:6379"
  stripe_key: rk_test_PZv1eOQv6ER2Ko57DZI0AssP
  stripe_pubkey: pk_test_j6YqhiucO6AtABjPWjiZWwtV
  devise_secret_key: aaaa
  local_key: <%= ENV['LOCAL_KEY'] %>
  admin_email: alexanmtz@gmail.com
  admin_email_alt: ola@truppie.com
  amadeus_api_key: <%= ENV['AMADEUS_API_KEY'] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV["facebook_id"] %>
  facebook_secret: <%= ENV["facebook_secret"] %>
  facebook_sdk: <%= ENV["FACEBOOK_SDK"] %>
  truppiemail_domain: <%= ENV["truppiemail_domain"] %>
  truppiemail_username: <%= ENV['SENDGRID_USERNAME'] %>
  truppiemail_password: <%= ENV['SENDGRID_PASSWORD'] %>
  moip_domain: <%= ENV['MOIP_DOMAIN'] %>
  moip_env: <%= ENV['MOIP_ENV'] %>
  moip_app_token: <%= ENV['MOIP_APP_TOKEN'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  stripe_key: <%= ENV['STRIPE_KEY'] %>
  stripe_pubkey: <%= ENV['STRIPE_PUBKEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  local_key: <%= ENV['LOCAL_KEY'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_email_alt: <%= ENV['ADMIN_EMAIL_ALT'] %>
  amadeus_api_key: <%= ENV['AMADEUS_API_KEY'] %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
